### ISSUE TITLE
[Epic] Add CAS authentication

### ISSUE THREAD

**Issue by theresnotime** [theresnotime/wmcs-uptime#25]
- [ ] Add [CAS SSO](https://wikitech.wikimedia.org/wiki/CAS-SSO) authentication
- [ ] Map LDAP accounts to local table for monitor/notification linking
- [ ] Remove internal authentication
